# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/shadowsocks/config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api.common.net import network_pb2 as common_dot_net_dot_network__pb2
from api.common.protocol import user_pb2 as common_dot_protocol_dot_user__pb2
from api.common.protocol import server_spec_pb2 as common_dot_protocol_dot_server__spec__pb2
from api.common.net.packetaddr import config_pb2 as common_dot_net_dot_packetaddr_dot_config__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proxy/shadowsocks/config.proto',
  package='v2ray.core.proxy.shadowsocks',
  syntax='proto3',
  serialized_options=b'\n com.v2ray.core.proxy.shadowsocksP\001Z0github.com/v2fly/v2ray-core/v5/proxy/shadowsocks\252\002\034V2Ray.Core.Proxy.Shadowsocks',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1eproxy/shadowsocks/config.proto\x12\x1cv2ray.core.proxy.shadowsocks\x1a\x18\x63ommon/net/network.proto\x1a\x1a\x63ommon/protocol/user.proto\x1a!common/protocol/server_spec.proto\x1a\"common/net/packetaddr/config.proto\"\x9a\x01\n\x07\x41\x63\x63ount\x12\x10\n\x08password\x18\x01 \x01(\t\x12=\n\x0b\x63ipher_type\x18\x02 \x01(\x0e\x32(.v2ray.core.proxy.shadowsocks.CipherType\x12\x10\n\x08iv_check\x18\x03 \x01(\x08\x12,\n\"experiment_reduced_iv_head_entropy\x18\x91\xbf\x05 \x01(\x08\"\xcc\x01\n\x0cServerConfig\x12\x17\n\x0budp_enabled\x18\x01 \x01(\x08\x42\x02\x18\x01\x12.\n\x04user\x18\x02 \x01(\x0b\x32 .v2ray.core.common.protocol.User\x12/\n\x07network\x18\x03 \x03(\x0e\x32\x1e.v2ray.core.common.net.Network\x12\x42\n\x0fpacket_encoding\x18\x04 \x01(\x0e\x32).v2ray.core.net.packetaddr.PacketAddrType\"J\n\x0c\x43lientConfig\x12:\n\x06server\x18\x01 \x03(\x0b\x32*.v2ray.core.common.protocol.ServerEndpoint*\\\n\nCipherType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0f\n\x0b\x41\x45S_128_GCM\x10\x01\x12\x0f\n\x0b\x41\x45S_256_GCM\x10\x02\x12\x15\n\x11\x43HACHA20_POLY1305\x10\x03\x12\x08\n\x04NONE\x10\x04\x42u\n com.v2ray.core.proxy.shadowsocksP\x01Z0github.com/v2fly/v2ray-core/v5/proxy/shadowsocks\xaa\x02\x1cV2Ray.Core.Proxy.Shadowsocksb\x06proto3'
  ,
  dependencies=[common_dot_net_dot_network__pb2.DESCRIPTOR,common_dot_protocol_dot_user__pb2.DESCRIPTOR,common_dot_protocol_dot_server__spec__pb2.DESCRIPTOR,common_dot_net_dot_packetaddr_dot_config__pb2.DESCRIPTOR,])

_CIPHERTYPE = _descriptor.EnumDescriptor(
  name='CipherType',
  full_name='v2ray.core.proxy.shadowsocks.CipherType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AES_128_GCM', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AES_256_GCM', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CHACHA20_POLY1305', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NONE', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=629,
  serialized_end=721,
)
_sym_db.RegisterEnumDescriptor(_CIPHERTYPE)

CipherType = enum_type_wrapper.EnumTypeWrapper(_CIPHERTYPE)
UNKNOWN = 0
AES_128_GCM = 1
AES_256_GCM = 2
CHACHA20_POLY1305 = 3
NONE = 4



_ACCOUNT = _descriptor.Descriptor(
  name='Account',
  full_name='v2ray.core.proxy.shadowsocks.Account',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='password', full_name='v2ray.core.proxy.shadowsocks.Account.password', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cipher_type', full_name='v2ray.core.proxy.shadowsocks.Account.cipher_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='iv_check', full_name='v2ray.core.proxy.shadowsocks.Account.iv_check', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='experiment_reduced_iv_head_entropy', full_name='v2ray.core.proxy.shadowsocks.Account.experiment_reduced_iv_head_entropy', index=3,
      number=90001, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=344,
)


_SERVERCONFIG = _descriptor.Descriptor(
  name='ServerConfig',
  full_name='v2ray.core.proxy.shadowsocks.ServerConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='udp_enabled', full_name='v2ray.core.proxy.shadowsocks.ServerConfig.udp_enabled', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\030\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user', full_name='v2ray.core.proxy.shadowsocks.ServerConfig.user', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='network', full_name='v2ray.core.proxy.shadowsocks.ServerConfig.network', index=2,
      number=3, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='packet_encoding', full_name='v2ray.core.proxy.shadowsocks.ServerConfig.packet_encoding', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=551,
)


_CLIENTCONFIG = _descriptor.Descriptor(
  name='ClientConfig',
  full_name='v2ray.core.proxy.shadowsocks.ClientConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='server', full_name='v2ray.core.proxy.shadowsocks.ClientConfig.server', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=553,
  serialized_end=627,
)

_ACCOUNT.fields_by_name['cipher_type'].enum_type = _CIPHERTYPE
_SERVERCONFIG.fields_by_name['user'].message_type = common_dot_protocol_dot_user__pb2._USER
_SERVERCONFIG.fields_by_name['network'].enum_type = common_dot_net_dot_network__pb2._NETWORK
_SERVERCONFIG.fields_by_name['packet_encoding'].enum_type = common_dot_net_dot_packetaddr_dot_config__pb2._PACKETADDRTYPE
_CLIENTCONFIG.fields_by_name['server'].message_type = common_dot_protocol_dot_server__spec__pb2._SERVERENDPOINT
DESCRIPTOR.message_types_by_name['Account'] = _ACCOUNT
DESCRIPTOR.message_types_by_name['ServerConfig'] = _SERVERCONFIG
DESCRIPTOR.message_types_by_name['ClientConfig'] = _CLIENTCONFIG
DESCRIPTOR.enum_types_by_name['CipherType'] = _CIPHERTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Account = _reflection.GeneratedProtocolMessageType('Account', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNT,
  '__module__' : 'proxy.shadowsocks.config_pb2'
  # @@protoc_insertion_point(class_scope:v2ray.core.proxy.shadowsocks.Account)
  })
_sym_db.RegisterMessage(Account)

ServerConfig = _reflection.GeneratedProtocolMessageType('ServerConfig', (_message.Message,), {
  'DESCRIPTOR' : _SERVERCONFIG,
  '__module__' : 'proxy.shadowsocks.config_pb2'
  # @@protoc_insertion_point(class_scope:v2ray.core.proxy.shadowsocks.ServerConfig)
  })
_sym_db.RegisterMessage(ServerConfig)

ClientConfig = _reflection.GeneratedProtocolMessageType('ClientConfig', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTCONFIG,
  '__module__' : 'proxy.shadowsocks.config_pb2'
  # @@protoc_insertion_point(class_scope:v2ray.core.proxy.shadowsocks.ClientConfig)
  })
_sym_db.RegisterMessage(ClientConfig)


DESCRIPTOR._options = None
_SERVERCONFIG.fields_by_name['udp_enabled']._options = None
# @@protoc_insertion_point(module_scope)
