# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/net/packetaddr/config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/net/packetaddr/config.proto',
  package='v2ray.core.net.packetaddr',
  syntax='proto3',
  serialized_options=b'\n$com.v2ray.core.common.net.packetaddrP\001Z4github.com/v2fly/v2ray-core/v5/common/net/packetaddr\252\002 V2Ray.Core.Common.Net.Packetaddr',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"common/net/packetaddr/config.proto\x12\x19v2ray.core.net.packetaddr*&\n\x0ePacketAddrType\x12\x08\n\x04None\x10\x00\x12\n\n\x06Packet\x10\x01\x42\x81\x01\n$com.v2ray.core.common.net.packetaddrP\x01Z4github.com/v2fly/v2ray-core/v5/common/net/packetaddr\xaa\x02 V2Ray.Core.Common.Net.Packetaddrb\x06proto3'
)

_PACKETADDRTYPE = _descriptor.EnumDescriptor(
  name='PacketAddrType',
  full_name='v2ray.core.net.packetaddr.PacketAddrType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='None', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Packet', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=65,
  serialized_end=103,
)
_sym_db.RegisterEnumDescriptor(_PACKETADDRTYPE)

PacketAddrType = enum_type_wrapper.EnumTypeWrapper(_PACKETADDRTYPE)
globals()['None'] = 0
Packet = 1


DESCRIPTOR.enum_types_by_name['PacketAddrType'] = _PACKETADDRTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
