# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api.app.instman.command import command_pb2 as app_dot_instman_dot_command_dot_command__pb2


class InstanceManagementServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListInstance = channel.unary_unary(
                '/v2ray.core.app.instman.command.InstanceManagementService/ListInstance',
                request_serializer=app_dot_instman_dot_command_dot_command__pb2.ListInstanceReq.SerializeToString,
                response_deserializer=app_dot_instman_dot_command_dot_command__pb2.ListInstanceResp.FromString,
                )
        self.AddInstance = channel.unary_unary(
                '/v2ray.core.app.instman.command.InstanceManagementService/AddInstance',
                request_serializer=app_dot_instman_dot_command_dot_command__pb2.AddInstanceReq.SerializeToString,
                response_deserializer=app_dot_instman_dot_command_dot_command__pb2.AddInstanceResp.FromString,
                )
        self.StartInstance = channel.unary_unary(
                '/v2ray.core.app.instman.command.InstanceManagementService/StartInstance',
                request_serializer=app_dot_instman_dot_command_dot_command__pb2.StartInstanceReq.SerializeToString,
                response_deserializer=app_dot_instman_dot_command_dot_command__pb2.StartInstanceResp.FromString,
                )


class InstanceManagementServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InstanceManagementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInstance,
                    request_deserializer=app_dot_instman_dot_command_dot_command__pb2.ListInstanceReq.FromString,
                    response_serializer=app_dot_instman_dot_command_dot_command__pb2.ListInstanceResp.SerializeToString,
            ),
            'AddInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.AddInstance,
                    request_deserializer=app_dot_instman_dot_command_dot_command__pb2.AddInstanceReq.FromString,
                    response_serializer=app_dot_instman_dot_command_dot_command__pb2.AddInstanceResp.SerializeToString,
            ),
            'StartInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.StartInstance,
                    request_deserializer=app_dot_instman_dot_command_dot_command__pb2.StartInstanceReq.FromString,
                    response_serializer=app_dot_instman_dot_command_dot_command__pb2.StartInstanceResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v2ray.core.app.instman.command.InstanceManagementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InstanceManagementService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/v2ray.core.app.instman.command.InstanceManagementService/ListInstance',
            app_dot_instman_dot_command_dot_command__pb2.ListInstanceReq.SerializeToString,
            app_dot_instman_dot_command_dot_command__pb2.ListInstanceResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/v2ray.core.app.instman.command.InstanceManagementService/AddInstance',
            app_dot_instman_dot_command_dot_command__pb2.AddInstanceReq.SerializeToString,
            app_dot_instman_dot_command_dot_command__pb2.AddInstanceResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/v2ray.core.app.instman.command.InstanceManagementService/StartInstance',
            app_dot_instman_dot_command_dot_command__pb2.StartInstanceReq.SerializeToString,
            app_dot_instman_dot_command_dot_command__pb2.StartInstanceResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
