# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/socks/simplified/config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api.common.protoext import extensions_pb2 as common_dot_protoext_dot_extensions__pb2
from api.common.net import address_pb2 as common_dot_net_dot_address__pb2
from api.common.net.packetaddr import config_pb2 as common_dot_net_dot_packetaddr_dot_config__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proxy/socks/simplified/config.proto',
  package='v2ray.core.proxy.socks.simplified',
  syntax='proto3',
  serialized_options=b'\n%com.v2ray.core.proxy.socks.simplifiedP\001Z5github.com/v2fly/v2ray-core/v5/proxy/socks/simplified\252\002!V2Ray.Core.Proxy.Socks.Simplified',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n#proxy/socks/simplified/config.proto\x12!v2ray.core.proxy.socks.simplified\x1a common/protoext/extensions.proto\x1a\x18\x63ommon/net/address.proto\x1a\"common/net/packetaddr/config.proto\"\xb5\x01\n\x0cServerConfig\x12\x32\n\x07\x61\x64\x64ress\x18\x03 \x01(\x0b\x32!.v2ray.core.common.net.IPOrDomain\x12\x13\n\x0budp_enabled\x18\x04 \x01(\x08\x12\x42\n\x0fpacket_encoding\x18\x07 \x01(\x0e\x32).v2ray.core.net.packetaddr.PacketAddrType:\x18\x82\xb5\x18\t\n\x07inbound\x82\xb5\x18\x07\x12\x05socks\"k\n\x0c\x43lientConfig\x12\x32\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0b\x32!.v2ray.core.common.net.IPOrDomain\x12\x0c\n\x04port\x18\x02 \x01(\r:\x19\x82\xb5\x18\n\n\x08outbound\x82\xb5\x18\x07\x12\x05socksB\x84\x01\n%com.v2ray.core.proxy.socks.simplifiedP\x01Z5github.com/v2fly/v2ray-core/v5/proxy/socks/simplified\xaa\x02!V2Ray.Core.Proxy.Socks.Simplifiedb\x06proto3'
  ,
  dependencies=[common_dot_protoext_dot_extensions__pb2.DESCRIPTOR,common_dot_net_dot_address__pb2.DESCRIPTOR,common_dot_net_dot_packetaddr_dot_config__pb2.DESCRIPTOR,])




_SERVERCONFIG = _descriptor.Descriptor(
  name='ServerConfig',
  full_name='v2ray.core.proxy.socks.simplified.ServerConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='v2ray.core.proxy.socks.simplified.ServerConfig.address', index=0,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='udp_enabled', full_name='v2ray.core.proxy.socks.simplified.ServerConfig.udp_enabled', index=1,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='packet_encoding', full_name='v2ray.core.proxy.socks.simplified.ServerConfig.packet_encoding', index=2,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\202\265\030\t\n\007inbound\202\265\030\007\022\005socks',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=352,
)


_CLIENTCONFIG = _descriptor.Descriptor(
  name='ClientConfig',
  full_name='v2ray.core.proxy.socks.simplified.ClientConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='v2ray.core.proxy.socks.simplified.ClientConfig.address', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='v2ray.core.proxy.socks.simplified.ClientConfig.port', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\202\265\030\n\n\010outbound\202\265\030\007\022\005socks',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=461,
)

_SERVERCONFIG.fields_by_name['address'].message_type = common_dot_net_dot_address__pb2._IPORDOMAIN
_SERVERCONFIG.fields_by_name['packet_encoding'].enum_type = common_dot_net_dot_packetaddr_dot_config__pb2._PACKETADDRTYPE
_CLIENTCONFIG.fields_by_name['address'].message_type = common_dot_net_dot_address__pb2._IPORDOMAIN
DESCRIPTOR.message_types_by_name['ServerConfig'] = _SERVERCONFIG
DESCRIPTOR.message_types_by_name['ClientConfig'] = _CLIENTCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServerConfig = _reflection.GeneratedProtocolMessageType('ServerConfig', (_message.Message,), {
  'DESCRIPTOR' : _SERVERCONFIG,
  '__module__' : 'proxy.socks.simplified.config_pb2'
  # @@protoc_insertion_point(class_scope:v2ray.core.proxy.socks.simplified.ServerConfig)
  })
_sym_db.RegisterMessage(ServerConfig)

ClientConfig = _reflection.GeneratedProtocolMessageType('ClientConfig', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTCONFIG,
  '__module__' : 'proxy.socks.simplified.config_pb2'
  # @@protoc_insertion_point(class_scope:v2ray.core.proxy.socks.simplified.ClientConfig)
  })
_sym_db.RegisterMessage(ClientConfig)


DESCRIPTOR._options = None
_SERVERCONFIG._options = None
_CLIENTCONFIG._options = None
# @@protoc_insertion_point(module_scope)
