# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/taggedfeatures/skeleton.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/taggedfeatures/skeleton.proto',
  package='v2ray.core.common.taggedfeatures',
  syntax='proto3',
  serialized_options=b'\n$com.v2ray.core.common.taggedfeaturesP\001Z4github.com/v2fly/v2ray-core/v5/common/taggedfeatures\252\002 V2Ray.Core.Common.Taggedfeatures',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$common/taggedfeatures/skeleton.proto\x12 v2ray.core.common.taggedfeatures\x1a\x19google/protobuf/any.proto\"\x99\x01\n\x06\x43onfig\x12H\n\x08\x66\x65\x61tures\x18\x01 \x03(\x0b\x32\x36.v2ray.core.common.taggedfeatures.Config.FeaturesEntry\x1a\x45\n\rFeaturesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any:\x02\x38\x01\x42\x81\x01\n$com.v2ray.core.common.taggedfeaturesP\x01Z4github.com/v2fly/v2ray-core/v5/common/taggedfeatures\xaa\x02 V2Ray.Core.Common.Taggedfeaturesb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_CONFIG_FEATURESENTRY = _descriptor.Descriptor(
  name='FeaturesEntry',
  full_name='v2ray.core.common.taggedfeatures.Config.FeaturesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='v2ray.core.common.taggedfeatures.Config.FeaturesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='v2ray.core.common.taggedfeatures.Config.FeaturesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=255,
)

_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='v2ray.core.common.taggedfeatures.Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='features', full_name='v2ray.core.common.taggedfeatures.Config.features', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CONFIG_FEATURESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=255,
)

_CONFIG_FEATURESENTRY.fields_by_name['value'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_CONFIG_FEATURESENTRY.containing_type = _CONFIG
_CONFIG.fields_by_name['features'].message_type = _CONFIG_FEATURESENTRY
DESCRIPTOR.message_types_by_name['Config'] = _CONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), {

  'FeaturesEntry' : _reflection.GeneratedProtocolMessageType('FeaturesEntry', (_message.Message,), {
    'DESCRIPTOR' : _CONFIG_FEATURESENTRY,
    '__module__' : 'common.taggedfeatures.skeleton_pb2'
    # @@protoc_insertion_point(class_scope:v2ray.core.common.taggedfeatures.Config.FeaturesEntry)
    })
  ,
  'DESCRIPTOR' : _CONFIG,
  '__module__' : 'common.taggedfeatures.skeleton_pb2'
  # @@protoc_insertion_point(class_scope:v2ray.core.common.taggedfeatures.Config)
  })
_sym_db.RegisterMessage(Config)
_sym_db.RegisterMessage(Config.FeaturesEntry)


DESCRIPTOR._options = None
_CONFIG_FEATURESENTRY._options = None
# @@protoc_insertion_point(module_scope)
