# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/protoext/testing/test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api.common.protoext import extensions_pb2 as common_dot_protoext_dot_extensions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/protoext/testing/test.proto',
  package='v2ray.core.common.protoext.testing',
  syntax='proto3',
  serialized_options=b'\n&com.v2ray.core.common.protoext.testingP\001Z3github.com/v2fly/v2ray-core/common/protoext/testing\252\002\"V2Ray.Core.Common.ProtoExt.Testing',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"common/protoext/testing/test.proto\x12\"v2ray.core.common.protoext.testing\x1a common/protoext/extensions.proto\"R\n\x0eTestingMessage\x12)\n\ntest_field\x18\x01 \x01(\tB\x15\x82\xb5\x18\x06\x12\x04test\x82\xb5\x18\x07\x12\x05test2:\x15\x82\xb5\x18\x06\n\x04\x64\x65mo\x82\xb5\x18\x07\n\x05\x64\x65mo2B\x84\x01\n&com.v2ray.core.common.protoext.testingP\x01Z3github.com/v2fly/v2ray-core/common/protoext/testing\xaa\x02\"V2Ray.Core.Common.ProtoExt.Testingb\x06proto3'
  ,
  dependencies=[common_dot_protoext_dot_extensions__pb2.DESCRIPTOR,])




_TESTINGMESSAGE = _descriptor.Descriptor(
  name='TestingMessage',
  full_name='v2ray.core.common.protoext.testing.TestingMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='test_field', full_name='v2ray.core.common.protoext.testing.TestingMessage.test_field', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\202\265\030\006\022\004test\202\265\030\007\022\005test2', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\202\265\030\006\n\004demo\202\265\030\007\n\005demo2',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=190,
)

DESCRIPTOR.message_types_by_name['TestingMessage'] = _TESTINGMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestingMessage = _reflection.GeneratedProtocolMessageType('TestingMessage', (_message.Message,), {
  'DESCRIPTOR' : _TESTINGMESSAGE,
  '__module__' : 'common.protoext.testing.test_pb2'
  # @@protoc_insertion_point(class_scope:v2ray.core.common.protoext.testing.TestingMessage)
  })
_sym_db.RegisterMessage(TestingMessage)


DESCRIPTOR._options = None
_TESTINGMESSAGE.fields_by_name['test_field']._options = None
_TESTINGMESSAGE._options = None
# @@protoc_insertion_point(module_scope)
