# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/commander/config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from api.common.protoext import extensions_pb2 as common_dot_protoext_dot_extensions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='app/commander/config.proto',
  package='v2ray.core.app.commander',
  syntax='proto3',
  serialized_options=b'\n\034com.v2ray.core.app.commanderP\001Z,github.com/v2fly/v2ray-core/v5/app/commander\252\002\030V2Ray.Core.App.Commander',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1a\x61pp/commander/config.proto\x12\x18v2ray.core.app.commander\x1a\x19google/protobuf/any.proto\x1a common/protoext/extensions.proto\"<\n\x06\x43onfig\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12%\n\x07service\x18\x02 \x03(\x0b\x32\x14.google.protobuf.Any\"5\n\x10ReflectionConfig:!\x82\xb5\x18\r\n\x0bgrpcservice\x82\xb5\x18\x0c\x12\nreflection\"K\n\x10SimplifiedConfig\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x03(\t:\x1c\x82\xb5\x18\t\n\x07service\x82\xb5\x18\x0b\x12\tcommanderBi\n\x1c\x63om.v2ray.core.app.commanderP\x01Z,github.com/v2fly/v2ray-core/v5/app/commander\xaa\x02\x18V2Ray.Core.App.Commanderb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,common_dot_protoext_dot_extensions__pb2.DESCRIPTOR,])




_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='v2ray.core.app.commander.Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag', full_name='v2ray.core.app.commander.Config.tag', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='service', full_name='v2ray.core.app.commander.Config.service', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=177,
)


_REFLECTIONCONFIG = _descriptor.Descriptor(
  name='ReflectionConfig',
  full_name='v2ray.core.app.commander.ReflectionConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\202\265\030\r\n\013grpcservice\202\265\030\014\022\nreflection',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=232,
)


_SIMPLIFIEDCONFIG = _descriptor.Descriptor(
  name='SimplifiedConfig',
  full_name='v2ray.core.app.commander.SimplifiedConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag', full_name='v2ray.core.app.commander.SimplifiedConfig.tag', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='v2ray.core.app.commander.SimplifiedConfig.name', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\202\265\030\t\n\007service\202\265\030\013\022\tcommander',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=309,
)

_CONFIG.fields_by_name['service'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['Config'] = _CONFIG
DESCRIPTOR.message_types_by_name['ReflectionConfig'] = _REFLECTIONCONFIG
DESCRIPTOR.message_types_by_name['SimplifiedConfig'] = _SIMPLIFIEDCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), {
  'DESCRIPTOR' : _CONFIG,
  '__module__' : 'app.commander.config_pb2'
  # @@protoc_insertion_point(class_scope:v2ray.core.app.commander.Config)
  })
_sym_db.RegisterMessage(Config)

ReflectionConfig = _reflection.GeneratedProtocolMessageType('ReflectionConfig', (_message.Message,), {
  'DESCRIPTOR' : _REFLECTIONCONFIG,
  '__module__' : 'app.commander.config_pb2'
  # @@protoc_insertion_point(class_scope:v2ray.core.app.commander.ReflectionConfig)
  })
_sym_db.RegisterMessage(ReflectionConfig)

SimplifiedConfig = _reflection.GeneratedProtocolMessageType('SimplifiedConfig', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLIFIEDCONFIG,
  '__module__' : 'app.commander.config_pb2'
  # @@protoc_insertion_point(class_scope:v2ray.core.app.commander.SimplifiedConfig)
  })
_sym_db.RegisterMessage(SimplifiedConfig)


DESCRIPTOR._options = None
_REFLECTIONCONFIG._options = None
_SIMPLIFIEDCONFIG._options = None
# @@protoc_insertion_point(module_scope)
